export const SET_ERROR ='SET_ERROR'
export const SET_ERROR_SUCCESS ='SET_ERROR_SUCCESS'
export const SET_SUCCESS = "SET_SUCCESS"
export const CLEAR_ERROR = "CLEAR_ERROR"
export const CLEAR_SUCCESS = "CLEAR_SUCCESS"

